### ISSUE TITLE
unable to get models files

### ISSUE THREAD

**Issue by hotwa** [zhenglz/OnionNet-SFCT#1]
I can't access website, http://jtmeng.sharelatex.top:9001/sfct_models/
is the port change?

**Comment by zhenglz** [comment]
Something wrong with the server, I am fixing it. But you could download the model files through the following link:

https://drive.google.com/drive/folders/1cSMvnwrAny0MkOn0AYGiDx0BbL5NSaV5?usp=sharing

Or using:
Web Link: https://pan.baidu.com/s/1bLBRYIGli9Y81iUvD5jf8g 
Access Code: 9in7 

Any problem, do let me know.
