### ISSUE TITLE
About the final trained model

### ISSUE THREAD

**Issue by zhuhui-in** [zhenglz/OnionNet-SFCT#2]
Hello, I have a few questions about the final model you provided on google drive. 
1. What is the training dataset of this model? whether contain crystal pose?
2. whether the model tested on the DUD-E dataset is same as the model you provided on google drive?
Thank you a lot.

**Comment by zhenglz** [comment]
1.The final model is trained with the dataset defined in Table 1 (dataset 5+dataset 1), including the crystal poses
2.The final model provided is used for DUD-E and DUD-AD data evaluation.
