### ISSUE TITLE
failed to download sfct.model 

### ISSUE THREAD

**Issue by leaves520** [zhenglz/OnionNet-SFCT#7]
Hi zheng, I would like to reproduce the outcome about this paper, but failed to download the pretrained sfct model. I need some help from you, thanks

**Comment by zhenglz** [comment]
You may download the files through Baidu NetDisk
https://pan.baidu.com/s/1HKWFEzu7yDdBRny_veHFCA 
Access code: p79i 

Or through Google Drive
https://drive.google.com/drive/folders/1eXkQHSsmx_ui8I-pw1n0kS44v6gqZTd8?usp=sharing
