### ISSUE TITLE
Cannot get model files 

### ISSUE THREAD

**Issue by Le-Phung-Hien** [zhenglz/OnionNet-SFCT#8]
Dear team,

I am interested in using OnionNet-SFCT to score my screening. However, I cannot get the model files from http://jtmeng.sharelatex.top:9001/sfct_models/, even running install.sh cannot get the files.

I would like to ask if there is any other way to get the files?

**Comment by zhenglz** [comment]
The standard model file could found here: https://drive.google.com/file/d/1iiJvW4GBfg4D7LCuTRLKv9qnRYu5L2o5/view?usp=drive_link
